-- generated by Go script

data:extend({
	{
		type = "item-group",
		name = "signals_group_vs2",
		order = "g1",
		icon = "__virtual-signals-2-fork-color__/graphics/item-group/signals_group_vs2.png",
		icon_size = 128,
	},
})