-- generated by Go script

data:extend({
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-10",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-10.png",
					subgroup = "virtual-signal-number",
					order = "b_s[010]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-11",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-11.png",
					subgroup = "virtual-signal-number",
					order = "b_s[011]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-12",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-12.png",
					subgroup = "virtual-signal-number",
					order = "b_s[012]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-13",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-13.png",
					subgroup = "virtual-signal-number",
					order = "b_s[013]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-14",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-14.png",
					subgroup = "virtual-signal-number",
					order = "b_s[014]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-15",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-15.png",
					subgroup = "virtual-signal-number",
					order = "b_s[015]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-16",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-16.png",
					subgroup = "virtual-signal-number",
					order = "b_s[016]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-17",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-17.png",
					subgroup = "virtual-signal-number",
					order = "b_s[017]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-18",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-18.png",
					subgroup = "virtual-signal-number",
					order = "b_s[018]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-19",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-19.png",
					subgroup = "virtual-signal-number",
					order = "b_s[019]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-20",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-20.png",
					subgroup = "virtual-signal-number",
					order = "b_s[020]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-24",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-24.png",
					subgroup = "virtual-signal-number",
					order = "b_s[021]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-25",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-25.png",
					subgroup = "virtual-signal-number",
					order = "b_s[022]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-28",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-28.png",
					subgroup = "virtual-signal-number",
					order = "b_s[023]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-30",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-30.png",
					subgroup = "virtual-signal-number",
					order = "b_s[024]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-32",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-32.png",
					subgroup = "virtual-signal-number",
					order = "b_s[025]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-36",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-36.png",
					subgroup = "virtual-signal-number",
					order = "b_s[026]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-40",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-40.png",
					subgroup = "virtual-signal-number",
					order = "b_s[027]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-45",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-45.png",
					subgroup = "virtual-signal-number",
					order = "b_s[028]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-50",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-50.png",
					subgroup = "virtual-signal-number",
					order = "b_s[029]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-55",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-55.png",
					subgroup = "virtual-signal-number",
					order = "b_s[030]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-60",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-60.png",
					subgroup = "virtual-signal-number",
					order = "b_s[031]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-64",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-64.png",
					subgroup = "virtual-signal-number",
					order = "b_s[032]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-65",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-65.png",
					subgroup = "virtual-signal-number",
					order = "b_s[033]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-70",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-70.png",
					subgroup = "virtual-signal-number",
					order = "b_s[034]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-75",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-75.png",
					subgroup = "virtual-signal-number",
					order = "b_s[035]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-80",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-80.png",
					subgroup = "virtual-signal-number",
					order = "b_s[036]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-90",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-90.png",
					subgroup = "virtual-signal-number",
					order = "b_s[037]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-96",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-96.png",
					subgroup = "virtual-signal-number",
					order = "b_s[038]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal-100",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-number_signal-100.png",
					subgroup = "virtual-signal-number",
					order = "b_s[039]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-question",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-letter_question.png",
					subgroup = "virtual-signal-letter",
					order = "c_s[026]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-exclamation",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-letter_exclamation.png",
					subgroup = "virtual-signal-letter",
					order = "c_s[027]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-transparent",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/virtual-signal-color_transparent.png",
					subgroup = "virtual-signal-color",
					order = "d_s[000]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-on",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_on.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[000]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-off",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_off.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[001]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-min",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_min.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[002]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-max",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_max.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[003]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-in",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_in.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[004]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-out",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_out.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[005]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-yes",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_yes.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[006]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-no",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_no.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[007]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-tick",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_tick.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[008]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-tock",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn_tock.png",
					subgroup = "vs2-cmn",
					order = "d_vs2[10]_s[009]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-size",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_size.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[000]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-buffer",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_buffer.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[001]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-cur",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_cur.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[002]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-sum",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_sum.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[003]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-limit",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_limit.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[004]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-capacity",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_capacity.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[005]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-nil",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_nil.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[006]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-test",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_test.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[007]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-new",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_new.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[008]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-old",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_old.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[009]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-low",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_low.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[010]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-high",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_high.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[011]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-full",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_full.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[012]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-request",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_request.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[013]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-response",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_response.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[014]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-second",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_second.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[015]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-minute",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_minute.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[016]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-hour",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_hour.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[017]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-day",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_day.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[018]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-fuck",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_fuck.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[019]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-ok",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_ok.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[020]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-check",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_check.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[021]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-cloak",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_cloak.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[022]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-play",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_play.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[023]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-pause",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_pause.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[024]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-stop",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_stop.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[025]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-positive",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_positive.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[026]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-negative",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_negative.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[027]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-lock",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_lock.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[028]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-unlock",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_unlock.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[029]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-empty",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn2_empty.png",
					subgroup = "vs2-cmn2",
					order = "d_vs2[20]_s[030]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-size_small",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_size_small.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[000]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-size_medium",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_size_medium.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[001]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-size_large",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_size_large.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[002]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-size_extra_large",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_size_extra_large.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[003]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-size_xxl",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_size_xxl.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[004]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-sev_info",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_sev_info.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[005]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-sev_warn",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_sev_warn.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[006]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-sev_err",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_sev_err.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[007]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-sev_critical",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_sev_critical.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[008]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-alert",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_alert.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[009]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-trigger",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_trigger.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[010]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-if",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_if.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[011]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-else",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_else.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[012]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-var_x",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_var_x.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[013]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-var_y",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_var_y.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[014]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-var_z",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_var_z.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[015]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-var_w",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_var_w.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[016]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-color_r",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_color_r.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[017]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-color_g",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_color_g.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[018]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-color_b",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_color_b.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[019]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-action",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-cmn3_action.png",
					subgroup = "vs2-cmn3",
					order = "d_vs2[30]_s[020]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-eq",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_eq.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[000]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-neq",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_neq.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[001]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-aeq",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_aeq.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[002]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-gt",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_gt.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[003]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-lt",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_lt.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[004]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-ge",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_ge.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[005]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-le",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_le.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[006]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-plus",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_plus.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[007]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-minus",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_minus.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[008]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-plus_minus",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_plus_minus.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[009]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-percent",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_percent.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[010]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-percent_per_millie",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_percent_per_millie.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[011]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-one_percent",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_one_percent.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[012]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-geo_angle",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_geo_angle.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[013]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-geo_perpendicular",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_geo_perpendicular.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[014]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-geo_parallel",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_geo_parallel.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[015]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-geo_similar",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_geo_similar.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[016]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_lemni",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_lemni.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[017]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_func",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_func.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[018]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_delta",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_delta.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[019]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_sigma",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_sigma.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[020]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_golden",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_golden.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[021]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_pi",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_pi.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[022]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_e",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_e.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[023]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_i",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_i.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[024]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_j",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_j.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[025]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_k",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_k.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[026]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_integral",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_integral.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[027]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_derivative",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_derivative.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[028]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_power",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_power.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[029]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-algo_sqrt",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_algo_sqrt.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[030]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-empty_set",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-math_empty_set.png",
					subgroup = "vs2-math",
					order = "d_vs2[40]_s[031]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-alpha",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_alpha.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[000]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-beta",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_beta.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[001]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-gamma",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_gamma.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[002]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-delta",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_delta.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[003]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-epsilon",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_epsilon.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[004]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-zeta",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_zeta.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[005]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-eta",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_eta.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[006]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-theta",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_theta.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[007]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-iota",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_iota.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[008]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-kappa",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_kappa.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[009]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-lambda",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_lambda.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[010]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-mu",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_mu.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[011]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-nu",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_nu.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[012]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-xi",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_xi.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[013]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-omicron",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_omicron.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[014]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-pi",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_pi.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[015]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-rho",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_rho.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[016]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-sigma",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_sigma.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[017]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-tau",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_tau.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[018]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-upsilon",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_upsilon.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[019]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-phi",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_phi.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[020]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-chi",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_chi.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[021]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-psi",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_psi.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[022]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-omega",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-greek_omega.png",
					subgroup = "vs2-greek",
					order = "d_vs2[50]_s[023]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-stack",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_stack.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[000]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-gear",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_gear.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[001]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-gears",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_gears.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[002]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-load",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_load.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[003]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-unload",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_unload.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[004]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-train",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_train.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[005]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-ship",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_ship.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[006]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-rocket",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_rocket.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[007]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-bell_on",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_bell_on.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[008]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-bell_off",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_bell_off.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[009]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-puzzle",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_puzzle.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[010]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-left",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_left.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[011]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-right",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_right.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[012]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-up",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_up.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[013]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-down",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_down.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[014]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-planet",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_planet.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[015]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-location",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_location.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[016]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-plug",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_plug.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[017]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-power_exc",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_power_exc.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[018]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-power_ok",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_power_ok.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[019]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-power_bolt",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_power_bolt.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[020]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-wireless",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_wireless.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[021]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-signal",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_signal.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[022]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-broadcast",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_broadcast.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[023]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-satellite",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_satellite.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[024]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-satellite2",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_satellite2.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[025]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-micro",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_micro.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[026]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-liquid",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_liquid.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[027]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-not_liquid",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_not_liquid.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[028]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_bolt",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_bolt.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[029]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_fire",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_fire.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[030]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_cold",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_cold.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[031]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_moon",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_moon.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[032]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_sun",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_sun.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[033]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_water",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_water.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[034]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_leaf",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_leaf.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[035]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_wind",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_wind.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[036]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_explosion",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_explosion.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[037]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_atom",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_atom.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[038]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_solar",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_solar.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[039]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-env_tree",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_env_tree.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[040]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-science",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_science.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[041]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-microscope",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_microscope.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[042]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-dna",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_dna.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[043]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-wrigglers",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_wrigglers.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[044]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-biters",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_biters.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[045]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-bug",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_bug.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[046]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-bug_no",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_bug_no.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[047]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-bacterium",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_bacterium.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[048]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-worm",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_worm.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[049]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-arrow_right_from_bracket",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_arrow_right_from_bracket.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[050]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-arrow_right_to_bracket",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_arrow_right_to_bracket.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[051]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-caret_left",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_caret_left.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[052]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-caret_right",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_caret_right.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[053]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-rotate_left",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_rotate_left.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[054]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-rotate",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_rotate.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[055]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-rotate_right",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_rotate_right.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[056]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-recycle",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_recycle.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[057]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-shuffle",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_shuffle.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[058]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-arrow-up-down",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_arrow-up-down.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[059]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-arrow-left-right",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_arrow-left-right.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[060]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-thermometer",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_thermometer.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[061]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-weight",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_weight.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[062]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-motor",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_motor.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[063]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-battery_empty",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_battery_empty.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[064]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-battery_quarter",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_battery_quarter.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[065]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-battery_half",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_battery_half.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[066]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-battery_three_quarters",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_battery_three_quarters.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[067]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-battery_full",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_battery_full.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[068]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-warning",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_warning.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[069]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-radioactive",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_radioactive.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[070]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-biohazard",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_biohazard.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[071]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-skull",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_skull.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[072]",
					hidden = true
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-package",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_package.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[073]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-circles-overlap-3",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_circles-overlap-3.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[074]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-user-astronaut",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_user-astronaut.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[075]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-pump-impeller",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_pump-impeller.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[076]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-spiral",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_spiral.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[077]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-volume-xmark",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_volume-xmark.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[078]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-volume-off",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_volume-off.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[079]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-volume-low",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_volume-low.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[080]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-volume",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_volume.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[081]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-volume-high",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_volume-high.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[082]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-triangle",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_triangle.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[083]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-square",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_square.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[084]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-pentagon",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_pentagon.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[085]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-hexagon",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_hexagon.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[086]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-septagon",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_septagon.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[087]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-octagon",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_octagon.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[088]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-circle",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-fa_circle.png",
					subgroup = "vs2-fa",
					order = "d_vs2[60]_s[089]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led0",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led0.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[000]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led1",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led1.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[001]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led2",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led2.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[002]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led3",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led3.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[003]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led4",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led4.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[004]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led5",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led5.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[005]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led6",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led6.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[006]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led7",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led7.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[007]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led8",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led8.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[008]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-led9",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_led9.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[009]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg0",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg0.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[010]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg1",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg1.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[011]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg2",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg2.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[012]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg3",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg3.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[013]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg4",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg4.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[014]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg5",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg5.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[015]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg6",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg6.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[016]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg7",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg7.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[017]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg8",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg8.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[018]",
					hidden = false
					},
					{
					type = "virtual-signal",
					name = "signal-vs2-reg9",
					icon = "__virtual-signals-2-fork-color__/graphics/signal/vs2-registers_reg9.png",
					subgroup = "vs2-registers",
					order = "d_vs2[70]_s[019]",
					hidden = false
					},
})