-- generated by Go script

data:extend({
			{
			type = "item-subgroup",
			name = "vs2-cmn",
			group = "signals_group_vs2",
			order = settings.startup["vs2-cmn"].value,
			},
			{
			type = "item-subgroup",
			name = "vs2-cmn2",
			group = "signals_group_vs2",
			order = settings.startup["vs2-cmn2"].value,
			},
			{
			type = "item-subgroup",
			name = "vs2-cmn3",
			group = "signals_group_vs2",
			order = settings.startup["vs2-cmn3"].value,
			},
			{
			type = "item-subgroup",
			name = "vs2-math",
			group = "signals_group_vs2",
			order = settings.startup["vs2-math"].value,
			},
			{
			type = "item-subgroup",
			name = "vs2-greek",
			group = "signals_group_vs2",
			order = settings.startup["vs2-greek"].value,
			},
			{
			type = "item-subgroup",
			name = "vs2-fa",
			group = "signals_group_vs2",
			order = settings.startup["vs2-fa"].value,
			},
			{
			type = "item-subgroup",
			name = "vs2-registers",
			group = "signals_group_vs2",
			order = settings.startup["vs2-registers"].value,
			},
})